import { useDispatch } from "react-redux";
import { clearAiHashtags } from "../../redux/slices/feedSlice";
import { X, Hash } from "lucide-react";

/**
 * HashtagChips — animated, clickable hashtag chips generated by AI.
 *
 * Props:
 *   hashtags  {string[]}  — array of hashtag strings (e.g. ["#hackathon", "#CSSOC"])
 *   onSelect  {function}  — called with the hashtag string when user taps one
 */
export default function HashtagChips({ hashtags, onSelect }) {
    const dispatch = useDispatch();

    if (!hashtags || hashtags.length === 0) return null;

    return (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
            <div className="flex items-center justify-between mb-1.5">
                <span className="flex items-center gap-1 text-xs font-semibold text-slate-500">
                    <Hash className="w-3 h-3 text-violet-400" />
                    AI Hashtag Suggestions
                </span>
                <button
                    onClick={() => dispatch(clearAiHashtags())}
                    className="text-slate-600 hover:text-slate-400 transition-colors"
                >
                    <X className="w-3 h-3" />
                </button>
            </div>
            <div className="flex flex-wrap gap-1.5">
                {hashtags.map((tag) => (
                    <button
                        key={tag}
                        onClick={() => onSelect(tag)}
                        className="group px-2.5 py-1 bg-violet-600/15 hover:bg-violet-600/30 border border-violet-500/25 hover:border-violet-500/50 text-violet-300 hover:text-violet-200 text-xs font-semibold rounded-full transition-all duration-150"
                    >
                        {tag}
                        <span className="ml-1 opacity-0 group-hover:opacity-60 text-[10px]">+</span>
                    </button>
                ))}
            </div>
        </div>
    );
}
