import { useDispatch } from "react-redux";
import { clearAiHashtags } from "../../redux/slices/feedSlice";
import { X, Hash } from "lucide-react";

/**
 * HashtagChips — animated, clickable hashtag chips generated by AI.
 *
 * Props:
 *   hashtags  {string[]}  — array of hashtag strings (e.g. ["#hackathon", "#CSSOC"])
 *   onSelect  {function}  — called with the hashtag string when user taps one
 */
export default function HashtagChips({ hashtags, onSelect }) {
    const dispatch = useDispatch();

    if (!hashtags || hashtags.length === 0) return null;

    return (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
            <div className="flex items-center justify-between mb-1.5">
                <span className="flex items-center gap-1 text-xs font-semibold text-text-secondary-light dark:text-text-secondary-dark">
                    <Hash className="w-3 h-3 text-info" />
                    AI Hashtag Suggestions
                </span>
                <button
                    onClick={() => dispatch(clearAiHashtags())}
                    className="text-text-secondary-light transition-colors hover:text-text-primary-light dark:text-text-secondary-dark dark:hover:text-text-primary-dark"
                >
                    <X className="w-3 h-3" />
                </button>
            </div>
            <div className="flex flex-wrap gap-1.5">
                {hashtags.map((tag) => (
                    <button
                        key={tag}
                        onClick={() => onSelect(tag)}
                        className="group rounded-full border border-info/20 bg-info/10 px-2.5 py-1 text-xs font-semibold text-info transition-all duration-150 hover:border-info/40 hover:bg-info/15 hover:text-info"
                    >
                        {tag}
                        <span className="ml-1 opacity-0 group-hover:opacity-60 text-[10px]">+</span>
                    </button>
                ))}
            </div>
        </div>
    );
}
